version: '3.0'

services:


  mongo:
    image: mongo:4.2.23
    restart: always
    env_file:
      - ./metabase/config/mongo.env
    ports:
      - 27017:27017

  app:
    build:
      context: .
      dockerfile: app-dockerfile
  
  metabase:
    image: metabase/metabase:v0.45.1
    container_name: metabase_gces
    env_file:
      - ./metabase/config/metabase.env
    ports:
      - 3000:3000