version: 2 # CircleCI version
jobs:
  build:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/repo # Default working directory, where your project will be cloned
    steps:
      - checkout
      - run: docker-compose up -d
  test:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/repo # Default working directory, where your project will be cloned
    steps:
      - checkout
      - run: docker-compose run app-test
  publish:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/repo # Default working directory, where your project will be cloned
    steps:
      - checkout
      - run: docker-compose run -e MODE=PUBLISH -e PYPI_PASSWORD=$PYPI_PASSWORD app-publish 
  docs-build:
    
    # machine: true # Use a Linux VM instead of docker environment
    docker:
      - image: python:3.8

    steps:
      - checkout
      # - run:
      #     name: Mkdir Docs
      #     command: mkdir docs
      - run:
          name: Install dependencies
          command: pip3 install Sphinx==6.1.3
      - run:
          name: Build
          command: sphinx-quickstart docs --sep --project 'Trabalho GCES 2022.2' --author 'Paulo Gonçalves Lima' -r trabalho_individual_gces_2022_paulo -l en
      - run:
          name: Build HTML
          command: cd docs/ && make html
      - persist_to_workspace:
          root: docs/build
          paths: 
            - html
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "59:ad:fd:64:71:eb:81:01:6a:d7:1a:c9:0c:19:39:af"
      - checkout
      - attach_workspace:
          at: docs/_build
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@paulo.net"
            git config user.name "ci-build"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist docs

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - publish:
          requires:
            - build
      - docs-build
          # requires:
          #   - publish
      - docs-deploy:
          requires:
            - docs-build
