version: 2 # CircleCI version
jobs:
  build:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/repo # Default working directory, where your project will be cloned
    steps:
      - checkout
      - run: docker-compose up -d
  test:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/repo # Default working directory, where your project will be cloned
    steps:
      - checkout
      - run: docker-compose run app-test
  publish:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/repo # Default working directory, where your project will be cloned
    steps:
      - checkout
      - run: docker-compose run -e MODE=PUBLISH -e PYPI_PASSWORD=$PYPI_PASSWORD app-publish 
  docs-build:
    machine: true # Use a Linux VM instead of docker environment
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "59:ad:fd:64:71:eb:81:01:6a:d7:1a:c9:0c:19:39:af"
      - run:
          name: Install dependencies
          command: docker-compose run -e MODE=PUBLISH -e PYPI_PASSWORD=$PYPI_PASSWORD app-publish 
      - run:
          name: Build docs
          command: cd docs/ && make html
      - persist_to_workspace:
          root: docs/_build
          paths: 
            - html

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - publish:
          requires:
            - build
      - docs-build:
          requires:
            - publish
