version: 2 # CircleCI version
jobs:
  build:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/repo # Default working directory, where your project will be cloned
    steps:
      - checkout
      - run: docker-compose up -d
  test:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/repo # Default working directory, where your project will be cloned
    steps:
      - checkout
      - run: docker-compose run app-test
  publish:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/repo # Default working directory, where your project will be cloned
    steps:
      - checkout
      - run: docker-compose run -e MODE=PUBLISH -e PYPI_PASSWORD=$PYPI_PASSWORD app-publish 

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - test
      - build
          # requires:
          #   - test
      - publish
          # requires:
          #   - build
          #   - test
