name: CI-CD

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    permissions: write-all
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Python linters
        run: pip install black
      - name: Executar linters
        uses: wearerequired/lint-action@v2
        with:
          black: true
          black_auto_fix: true
  docker:
    needs: run-linters
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: app-dockerfile
          push: true
          tags: paulogoncalveslima/trabalho_gces:latest
